### ISSUE TITLE
Remove .py from handbook.py in usage

### ISSUE THREAD

**Issue by DannyBen** [uribench/software-engineering-handbook-tools#17]
There are leftovers from the days before the pip package

https://github.com/uribench/software-engineering-handbook-tools/blob/8497dc07aa783c34988efc7feaa3d9081a12967c/handbook_tools/handbook.py#L6-L9

**Comment by uribench** [comment]
I thought I removed them all. Will check. Thanks.

**Comment by uribench** [comment]
Done with pull request #19. Few leftovers found on usage of handbook.py and also on toc.py
