### ISSUE TITLE
Limit docopt lines to 80 characters or less

### ISSUE THREAD

**Issue by DannyBen** [uribench/software-engineering-handbook-tools#18]
This should probably be done in all subcommands, here is an example of an offending file and how it looks without limiting:

https://github.com/uribench/software-engineering-handbook-tools/blob/8497dc07aa783c34988efc7feaa3d9081a12967c/handbook_tools/handbook.py#L27-L35

![image](https://user-images.githubusercontent.com/2405099/42363764-69a6d45e-8101-11e8-912e-721443274452.png)

**Comment by uribench** [comment]
Difficult, but will be done
