### ISSUE TITLE
Command summaries line wrapping

### ISSUE THREAD

**Issue by DannyBen** [uribench/software-engineering-handbook-tools#2]
When running `./handbook.py --help` in an 80 column terminal, the command summary does not wrap properly. Although this "bug" is common among CLI utilities, it does not make it right.

![image](https://user-images.githubusercontent.com/2405099/41511300-f9e2d09c-727c-11e8-8ae3-c3e7c2f9f9ab.png)

I would suggest one of these options:

1. Shorten all summaries so that they fit inside an 80 column terminal
2. Hardcode the line wrapping at 80 columns (i.e. add `\n` where appropriate, and "engineer" the line wrapping)
3. (Best option in my view) Identify the terminal width, and wrap it automatically.

(I have implemented something similar in my [Colsole gem][1], provided here as reference and for inspiration)

[1]: https://github.com/DannyBen/colsole/blob/master/lib/colsole.rb#L98

**Comment by uribench** [comment]
Done using suggested option 1.
